### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by jackure** [alvarobartt/trendet#10]
`pip install trendet
Collecting trendet
  Downloading trendet-0.6.tar.gz (10 kB)
    ERROR: Command errored out with exit status 1:
     command: 'd:\programas\python37\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\x\\AppData\\Local\\Temp\\pip-install-bq8c2po4\\trendet\\setup.py'"'"'; __file__='"'"'C:\\Users\\x\\AppData\\Local\\Temp\\pip-install-bq8c2po4\\trendet\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\x\AppData\Local\Temp\pip-pip-egg-info-tk2aj33h'
         cwd: C:\Users\x\AppData\Local\Temp\pip-install-bq8c2po4\trendet\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\x\AppData\Local\Temp\pip-install-bq8c2po4\trendet\setup.py", line 32, in <module>
        install_requires=requirements(),
      File "C:\Users\x\AppData\Local\Temp\pip-install-bq8c2po4\trendet\setup.py", line 14, in requirements
        with io.open('requirements.txt', encoding='utf-8') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

Simillar to [https://github.com/alvarobartt/investpy/issues/85](https://github.com/alvarobartt/investpy/issues/85)

I have tried:
- python -m pip install trendet
- python -m pip install trendet==0.6
- python -m pip install trendet==0.6 --upgrade --user
- python -m pip install trendet-0.6.tar.gz

I also tried to pre-install the requirements
`sphinx==2.4.4
sphinx_rtd_theme==0.4.3
recommonmark==0.6.0`

**Comment by jackure** [comment]
### I have finally found the solution!
Maybe for someone else can be useful :)

`pip install git+https://github.com/alvarobartt/trendet.git@master`

**Comment by alvarobartt** [comment]
Hi @jackure, thank you for reporting this issue! As you already said, there was an error related to the 0.6 trendet release which was also reported in #9. I already fixed it on the package, since the `requirements.txt` file was not included in the `MANIFEST.in` so that the installation process was erroring.

The command you propose fixes it, but I will release the 0.7 version probably tomorrow, with some new features and bug fixes.

I will consider this issue closed until the 0.7 release comes out. __Remember to STAR THE REPOif you found it useful and FOLLOW ME at GitHub so as to get notified of all the updates!__
